# Generated by Django 5.2.8 on 2025-11-24 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency_ghz", models.DecimalField(decimal_places=2, max_digits=5)),
                ("capacity_mbps", models.PositiveIntegerField()),
                (
                    "vendor",
                    models.CharField(
                        choices=[("CERAGON", "Ceragon"), ("OTHER", "Other")],
                        default="CERAGON",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DOWN", "Down"),
                            ("PLANNED", "Planned"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_a",
                        to="core.site",
                    ),
                ),
                (
                    "site_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_b",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["vendor"], name="core_link_vendor_e0b23f_idx"),
                    models.Index(fields=["status"], name="core_link_status_cebb51_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("site_a", models.F("site_b")), _negated=True
                        ),
                        name="link_not_loop",
                    )
                ],
            },
        ),
    ]
